### ISSUE TITLE
Handle moving files

### ISSUE THREAD

**Issue by renchap** [renchap/shrine-google_cloud_storage#1]
We cant rename files in GCS, but we can copy it and delete the previous one.

**Comment by janko-m** [comment]
I think this one is not necessary, notice that Shrine::Storage::S3 doesn't have it either. The "moving" functionality is in my opinion only really useful as a performance optimization (e.g. `mv` on filesystem which is always instant, unlike `cp`), users can still get the same "copy" + "delete" functionality by using the `delete_promoted` plugin (and shrine-google_cloud_storage will already automatically perform "copy" when it can).

**Comment by renchap** [comment]
Yes, now that upload supports copy all should be ok.
