### ISSUE TITLE
Cannot remove a model with missing file

### ISSUE THREAD

**Issue by d4rky-pl** [renchap/shrine-google_cloud_storage#13]
When trying to remove a model that is missing a file, the library crashes with

```
Caught error notFound: Not Found
Error - #<Google::Apis::ClientError: notFound: Not Found>
```

**Comment by renchap** [comment]
What do you mean by "missing a file"? The shrine field in the database contains data about a file stored in GCS, but the file has been deleted from GCS and the database record not updated?

**Comment by renchap** [comment]
I am closing it, feel free to reopen it with the details I asked above.
