### ISSUE TITLE
Use skip_lookup option

### ISSUE THREAD

**Issue by trebor8x** [renchap/shrine-google_cloud_storage#21]
Hi there,

I noticed an issue when uploading a file using a service account with the role `storage object administrator` (!= `storage administrator`).
The upload fails when accessing the bucket in `#get_bucket`.
The `google-cloud-storage` gem provides a solution in form of the `skip_lookup` option:

```ruby
storage = Google::Cloud::Storage.new
bucket = storage.bucket "sample-bucket" # raises
Google::Cloud::PermissionDeniedError: forbidden:  ... iam.gserviceaccount.com does not have storage.buckets.get access to sample-bucket

bucket = storage.bucket "sample-bucket", skip_lookup: true
=> #<Google::Cloud::Storage::Bucket:0x00...>
```
Do you see any issues with using the `skip_lookup` option in `shrine-google_cloud_storage` ?

More info can be found here: https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1588

**Comment by renchap** [comment]
Thanks for your report!
I need to check where `get_bucket` is used and where `skip_lookup: true` can safely be used. It might be useful to check a bucket exist and handle a non-existent bucket in this gem rather than with a `Google::Cloud` exception.
I will have a look at it. If you want to tackle this and send a PR, feel free!

**Comment by trebor8x** [comment]
Thanks for the quick response.
For the time being I promoted the service-account to be a `storage administrator` and uploads work fine.
In my opinion a `storage object administrator` role should suffice to upload / delete files though.
I am fairly new to this project (and shrine) so I would prefer, if you could have a look  @renchap

**Comment by renchap** [comment]
As we are only working on files, not buckets, it makes sense to never instanciate a proper `Bucket` object. It also avoids one API call for each file operation, which is very good for performance. The only downside is that if the bucket is not set up properly the request will fail and an exception will be raised, but this should not happen often.

I made the change on `master`, can you confirm that it also fixes your issue?

**Comment by trebor8x** [comment]
I can confirm that uploads with a `storage object administrator` are working with the current master.
Nicely done!
