### ISSUE TITLE
ArgumentError: project_id is missing

### ISSUE THREAD

**Issue by Shahbazchandio** [renchap/shrine-google_cloud_storage#28]
Getting ArgumentError: project_id is missing in syslog sidekiq on submitting. Also the images are not bieng processed in the Background.
my .env:- 
 GCS_BUCKET='Bucket Name'
 GOOGLE_CLOUD_PROJECT="Project Name"
 GOOGLE_APPLICATION_CREDENTIALS=./some-service.json

**Comment by renchap** [comment]
According to the GCS ruby documentation, your project needs to be specified in a `STORAGE_PROJECT` env variable: https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-storage/v1.12.0/guides/authentication
I would also suggest using an absolute path for the app credentials file to avoid any issues.
