### ISSUE TITLE
Publish a new version?

### ISSUE THREAD

**Issue by ianks** [renchap/shrine-google_cloud_storage#32]
I noticed that the published rubygems version is pretty far behind, which is breaking support for presigning urls. is there any chance you can publish an update?

**Comment by wzcolon** [comment]
OMG. I've been beating my head on this for hours. Thanks for the hint. 

`gem "shrine-google_cloud_storage", git: 'git@github.com:renchap/shrine-google_cloud_storage.git', branch: 'master'` for now.

**Comment by janko** [comment]
Just to check, what do you mean by "breaking support for presigning URLs"? Are you referring to the fact that the latest released version of `shrine-google_cloud_storage` doesn't yet work with Uppy (which is fixed in master)?

**Comment by renchap** [comment]
I just released 2.0.0!
