### ISSUE TITLE
Bump google-cloud-storage version

### ISSUE THREAD

**Issue by waclock** [renchap/shrine-google_cloud_storage#38]
The version used currently by the latest release is `1.7.1`, which depends on google-api-client 0.14.2, which is pretty far behind (causing issues integrating with bigquery specifically).

**Comment by renchap** [comment]
I am not sure to understand here. The dependency is:
https://github.com/renchap/shrine-google_cloud_storage/blob/8366c5e8aa0d9090b1eec7fdf2e86eb3537cc220/shrine-google_cloud_storage.gemspec#L17

So it allows the latest `google-cloud-storage` gem to be installed (1.21.1) as it matches the dependency specifier. In my own project I have `google-api-client` version 0.33.1 & `google-cloud-storage` version 1.21.1 without any issues.
